// styles.js
import { StyleSheet } from "react-native";

export const theme = {
  colors: {
    background: "#FAFAF8",
    surface: "#FFFFFF",
    surfaceElevated: "#F3F2EF",
    border: "#E2E0DB",
    borderMuted: "#EDEBE7",
    accent: "#1C1917",
    accentSoft: "#5C534A",
    text: "#1C1917",
    textMuted: "#6B6560",
    textDim: "#9A948C",
    danger: "#B42318",
    overlay: "rgba(28, 25, 23, 0.45)",
    divider: "#E8E5E1",
    success: "#3F6B4D",
  },
  radius: {
    sm: 6,
    md: 10,
    lg: 14,
    xl: 18,
    full: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 28,
  },
  fonts: {
    regular: "LibreBaskerville_400Regular",
    italic: "LibreBaskerville_400Regular_Italic",
    bold: "LibreBaskerville_700Bold",
  },
};

export const styles = StyleSheet.create({
  scrollContainer: {
    flex: 1,
    backgroundColor: theme.colors.background,
    alignSelf: "center",
    width: "100%",
  },
  scrollContent: {
    paddingHorizontal: theme.spacing.xl,
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.xxl,
    backgroundColor: theme.colors.background,
  },
  container: {
    justifyContent: "center",
    backgroundColor: theme.colors.background,
    alignItems: "center",
    flex: 1,
  },
  screen: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  screenContent: {
    flex: 1,
    backgroundColor: theme.colors.background,
    paddingHorizontal: theme.spacing.xl,
    paddingTop: theme.spacing.sm,
  },
  heading: {
    backgroundColor: theme.colors.background,
    paddingHorizontal: theme.spacing.xl,
    paddingTop: theme.spacing.lg,
    paddingBottom: theme.spacing.md,
    alignSelf: "stretch",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.divider,
  },
  headingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.sm,
  },
  headingText: {
    color: theme.colors.text,
    fontSize: 26,
    fontFamily: theme.fonts.bold,
    letterSpacing: -0.3,
    lineHeight: 34,
  },
  headingItalicsText: {
    color: theme.colors.accentSoft,
    fontSize: 26,
    fontFamily: theme.fonts.italic,
    letterSpacing: -0.3,
    lineHeight: 34,
  },
  headingSubtext: {
    color: theme.colors.textMuted,
    fontSize: 13,
    fontFamily: theme.fonts.regular,
    marginTop: theme.spacing.xs,
    lineHeight: 20,
  },
  sectionLabel: {
    color: theme.colors.textMuted,
    fontSize: 12,
    fontFamily: theme.fonts.bold,
    marginBottom: theme.spacing.sm,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  sectionSubtitle: {
    color: theme.colors.textMuted,
    fontSize: 13,
    fontFamily: theme.fonts.regular,
    lineHeight: 20,
    marginBottom: theme.spacing.md,
  },
  sectionHeader: {
    marginTop: theme.spacing.lg,
    marginBottom: theme.spacing.sm,
    paddingTop: theme.spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.divider,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: theme.colors.divider,
    alignSelf: "stretch",
    marginVertical: theme.spacing.lg,
  },
  button: {
    backgroundColor: theme.colors.accent,
    borderRadius: theme.radius.sm,
    marginVertical: theme.spacing.md,
    minHeight: 48,
    paddingHorizontal: theme.spacing.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonSecondary: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.sm,
    marginVertical: theme.spacing.md,
    minHeight: 48,
    paddingHorizontal: theme.spacing.lg,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontFamily: theme.fonts.bold,
    letterSpacing: 0.2,
  },
  buttonSecondaryText: {
    color: theme.colors.text,
    fontSize: 15,
    fontFamily: theme.fonts.bold,
    letterSpacing: 0.2,
  },
  buttonPressed: {
    opacity: 0.78,
  },
  profileImage: {
    width: "100%",
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surfaceElevated,
  },
  bodyTextLarge: {
    color: theme.colors.text,
    fontSize: 16,
    fontFamily: theme.fonts.bold,
    marginBottom: theme.spacing.sm,
  },
  bodyTextMed: {
    color: theme.colors.textMuted,
    fontSize: 14,
    fontFamily: theme.fonts.regular,
    lineHeight: 22,
  },
  bodyTextSmall: {
    color: theme.colors.textDim,
    fontSize: 12,
    fontFamily: theme.fonts.regular,
    lineHeight: 18,
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    overflow: "hidden",
    marginVertical: theme.spacing.sm,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: theme.spacing.xxl,
    paddingHorizontal: theme.spacing.lg,
  },
  emptyStateTitle: {
    color: theme.colors.text,
    fontSize: 18,
    fontFamily: theme.fonts.bold,
    textAlign: "center",
    marginBottom: theme.spacing.sm,
  },
  emptyStateText: {
    color: theme.colors.textMuted,
    fontSize: 14,
    fontFamily: theme.fonts.regular,
    textAlign: "center",
    lineHeight: 22,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: theme.radius.sm,
    alignItems: "center",
    justifyContent: "center",
    marginRight: theme.spacing.xs,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
  },
  badge: {
    alignSelf: "flex-start",
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.xs,
    borderRadius: theme.radius.sm,
    backgroundColor: theme.colors.surfaceElevated,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginTop: theme.spacing.sm,
  },
  badgeText: {
    color: theme.colors.accentSoft,
    fontSize: 12,
    fontFamily: theme.fonts.bold,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  inputField: {
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.md,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.md,
    minHeight: 48,
    justifyContent: "center",
  },
  picker: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    color: theme.colors.text,
    marginVertical: theme.spacing.sm,
  },
});
